### ISSUE TITLE
dynamico is not a function

### ISSUE THREAD

**Issue by Rondeveloper** [Soluto/dynamico#80]
I've started a new server according to the steps in 
[https://github.com/Soluto/dynamico/blob/master/server/readme.md#Storage]()

and got the error:
```
TypeError: dynamico is not a function
    at Object.<anonymous> (/Users/ronsivan/Documents/repos/dynamico-registry/index.js:6:28)
    at Module._compile (internal/modules/cjs/loader.js:778:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:789:10)
    at Module.load (internal/modules/cjs/loader.js:653:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:593:12)
    at Function.Module._load (internal/modules/cjs/loader.js:585:3)
    at Function.Module.runMain (internal/modules/cjs/loader.js:831:12)
    at startup (internal/bootstrap/node.js:283:19)
    at bootstrapNodeJSCore (internal/bootstrap/node.js:622:3)
```

**Comment by EladBezalel** [comment]
First of all hi and thanks for trying out Dynamico! :)

Could you please give us some more details, what storage are you trying to initiate?

You can take a look at this [codesandbox](url) which creates a server with filesystem storage

**Comment by Rondeveloper** [comment]
Hi :)
I am using filesystem storage, this is my index.js
```
const express = require('express')
const dynamicoMiddleware = require('@dynamico/express-middleware');
const { FSStorage } = require('@dynamico/fs-storage');
const PORT = process.env.PORT || 5000;

const storageProvider = new FSStorage('./components');
const dynamicoMiddleware = dynamico(storageProvider);

const app = express();
app.use('/api/components', dynamicoMiddleware(new FSStorage('./components')));
.listen(PORT, () => console.log(`Listening on ${ PORT }`))
```

**Comment by EladBezalel** [comment]
Looks like there's actually no `dynamico` variable and you are declaring `dynamicoMiddleware` twice..

Try this
```js
const express = require('express')
const dynamicoMiddleware = require('@dynamico/express-middleware');
const { FSStorage } = require('@dynamico/fs-storage');
const PORT = process.env.PORT || 5000;

const app = express();
app.use('/api/components', dynamicoMiddleware(new FSStorage('./components')));
.listen(PORT, () => console.log(`Listening on ${ PORT }`))
```

**Comment by Rondeveloper** [comment]
> Looks like there's actually no `dynamico` variable and you are declaring `dynamicoMiddleware` twice..
> 
> Try this
> 
> ```js
> const express = require('express')
> const dynamicoMiddleware = require('@dynamico/express-middleware');
> const { FSStorage } = require('@dynamico/fs-storage');
> const PORT = process.env.PORT || 5000;
> 
> const app = express();
> app.use('/api/components', dynamicoMiddleware(new FSStorage('./components')));
> .listen(PORT, () => console.log(`Listening on ${ PORT }`))
> ```

Ok, also added cors packaged and used it as shown in the codesandbox registry example.
It still shows the same error
`/Users/ronsivan/Documents/repos/secure-springs-95544/index.js:15
7:00:36 PM web.1 |  app.use('/api/components', cors(), dynamicoMiddleware(new FSStorage('./components')));
7:00:36 PM web.1 |                                     ^
7:00:36 PM web.1 |  TypeError: dynamicoMiddleware is not a function
7:00:36 PM web.1 |      at Object.<anonymous> (/Users/ronsivan/Documents/repos/secure-springs-95544/index.js:15:36)
7:00:36 PM web.1 |      at Module._compile (internal/modules/cjs/loader.js:778:30)
7:00:36 PM web.1 |      at Object.Module._extensions..js (internal/modules/cjs/loader.js:789:10)
7:00:36 PM web.1 |      at Module.load (internal/modules/cjs/loader.js:653:32)
7:00:36 PM web.1 |      at tryModuleLoad (internal/modules/cjs/loader.js:593:12)
7:00:36 PM web.1 |      at Function.Module._load (internal/modules/cjs/loader.js:585:3)
7:00:36 PM web.1 |      at Function.Module.runMain (internal/modules/cjs/loader.js:831:12)
7:00:36 PM web.1 |      at startup (internal/bootstrap/node.js:283:19)
7:00:36 PM web.1 |      at bootstrapNodeJSCore (internal/bootstrap/node.js:622:3)
[DONE] Killing all processes with signal  SIGINT
7:00:36 PM web.1 Exited with exit code null
`

**Comment by EladBezalel** [comment]
Can you please try and reproduce on codesandbox?

**Comment by eladav** [comment]
Hey @Rondeveloper, Can you please try adding to the require statement a reference to the default property? like so:
```js
const dynamicoMiddleware = require('@dynamico/express-middleware').default;
```

Since we're just building the code with typescript the way we export the package is not consistent with commonJS. It's a known issue and we plan to solve it in the near future.

Thanks for pointing that out. We'll open an issue and link it here.

**Comment by Rondeveloper** [comment]
> Hey @Rondeveloper, Can you please try adding to the require statement a reference to the default property? like so:
> 
> ```js
> const dynamicoMiddleware = require('@dynamico/express-middleware').default;
> ```
> 
> Since we're just building the code with typescript the way we export the package is not consistent with commonJS. It's a known issue and we plan to solve it in the near future.
> 
> Thanks for pointing that out. We'll open an issue and link it here.

Thanks for helping me out with this! @EladBezalel @eladav 
I attended the Duda meetup and since then I've been excited to try dynamico with the new React Native app I'm working on :)

**Comment by eladav** [comment]
Hey @Rondeveloper,
We're very happy to help :)

As part of our efforts to improve the framework we want to get your feedback on the integration process. We're always happy to get feedback in the form of issues, this helps us improve the product and allows others to contribute.

Also, If you're willing to jump on a quick call to tell us about your experience with setting Dynamico up that would be very helpful.

By the way, can we close this issue?

**Comment by Rondeveloper** [comment]
Yes, I'm closing it, I'll be glad to give feedback when I finish the whole setup process of the client/server
